# Generated by Django 5.0.6 on 2025-01-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_posted_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
